name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]

jobs:
  maven-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: maven
          server-id: central
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.gpg_private_key }}
          gpg-passphrase: GPG_PASSPHRASE
      - name: Unsnapshot version
        run: mvn versions:set -DremoveSnapshot
      - name: Configure Maven and deploy
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USER }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASS }}
          GPG_PASSPHRASE: ${{ secrets.gpg_passphrase }}
        run: mvn -B -Prelease deploy

  update-version:
    needs: [ maven-release ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      - name: Configure git
        run: |
          git config --global user.email "johan.roeleveld@praegus.nl"
          git config --global user.name "Praegus"
      - name: Update version
        run: |
          mvn -B release:update-versions -DautoVersionSubmodules=true
          git add pom.xml
          git commit -m "Update version"
          git push origin main